// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpngjqqwnemtedrafoqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbmdqcXF3bmVtdGVkcmFmb3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Njk3NjIsImV4cCI6MjA2NTE0NTc2Mn0.8YYq1MFv9wjJhlYmqQgg1m4eoKaPT3xKy2fTnuR33jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);